# Generated by Django 6.0.1 on 2026-02-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
